const regularEnglish = {
    level1: [
        "What was your first impression of me?",
        "What do you think is the hardest part of my job?",
        "Do I seem like a cat or dog person?",
        "What do my shoes tell you about me?",
        "Do I seem like more of a creative or analytical type? explain.",
        "How many speeding tickets do you think I've gotten in my life?",
        "What do you think I'm most likely to splurge on?",
        "Finish the sentence: just by looking at you I'd think ____.",
        "Do I remind you of anyone?",
        "Do you think I've ever checked an ex's phone for evidence?",
        "What's the first thing you noticed about me?",
        "Do I seem like a coffee or tea person? Sweetened or unsweetened?",
        "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
        "Do I look kind? explain.",
        "Do you think I fall in love easily? why or why not?",
        "As a child, what do you think I wanted to be?",
        "Do you think I'm usually early, on time, or late to events? explain.",
        "What subject do you think I thrived in at school? Did I fail any?",
        "What compliment do you think I hear the most?",
        "Do I seem like a morning person or a night owl? why?",
        "On a scale of 1-10, how messy do you think my car is? 1 being clean 10 complete disaster",
        "Do you think I was popular in school? explain.",
        "Do you think I intimidate others? why or why not?",
        "What about me is most strange or unfamiliar to you?",
        "What about me intrigues you?",
        "What does my style tell you about me?",
        "Do you think I've ever had my heart broken?",
        "Do you think I've been in love?",
        "What is the worst assumption someone has made about you?",
    ],
    
    level2: [
        "What is your defining characteristic?",
        "What's the most pain you've ever been in that wasn't physical?",
        "How are you, really?",
        "What is the last thing your mom has lied to you about?",
        "What's your father's name and one thing about him?",
        "What have I tolerated from people in the past that I no longer have space for?",
        "Something that brought a smile to my face this week was ___.",
        "What are you feeling a lot of lately?",
        "What do you need right now but aren't communicating?",
        "What are you currently working through that others don't see?",
        "What was the biggest turning point in your dating life?",
        "What is your heart telling you?",
        "What is your most toxic trait you can admit to?",
        "Who in your life deserves the biggest thank you? Let them know if you can.",
        "What are you overthinking right now?",
        "What did you last relationship teach you about yourself?",
        "What belief about yourself no longer serves you?",
        "What do you need to forgive yourself for?",
        "What's the hardest lesson you've learned in love?",
        "You hurt me, but thank you for ___.",
        "Who in your life can you be your most vulnerable with?",
        "Which one of your parent's personality traits do you want to keep/let go of?",
        "Dear younger self: ____.",
        "Think of someone you admire. Why did this person come to mind?",
        "Are you lying to yourself about anything?",
        "What's your favorite part of yourself that isn't physical?",
        "What's the hardest part about dating you?",
        "I feel loved when ___.",
        "What is something you've learned about yourself this week?",
        "Self love is ___.",
        "What was the lesson in your most recent painful experience?",
        "I know I'm in love when ___.",
        "What's your favorite song lyric you can think of off the top of your head?",
        "How did you get over your first love?",
        "What's the best lesson an ex has ever taught you?",
        "Is there anyone who's changed your life but doesn't know it?",
        "What do you need right now, more than anything?",
        "When was the last time you felt lucky to be you?",
        "What do you need to accept today?",
        "When was the last time you felt most yourself?",
        "What's your mother's name and the most valuable lesson she's taught you thus far?",
        "What are you most grateful for in this current moment?",
        "What are you still trying to prove to yourself?",
        "What have you been taking for granted lately?",
        "Is there a feeling you miss?",
        "What would your younger self not believe about your life today?",
        "If you could have it your way: Who would you be with? Where would you be? And what would you be doing?",
        "What do you need to hear right now?",
        "What title would you give this chapter in your life?",
        "What dating advice would you give your younger self?",
        "What lesson should you have learned by now?",
        "When was the last time you were able to use your pain to help someone else?",
        "What would you never want to change about yourself?",
        "What question did this year leave you with?",
        "What about yourself is hardest to admit?",
        "What question are you trying to answer most in your life right now?",
        "Finish the sentences: strangers would describe me as _____. Only I know that I am ______",
        "When you're asked how are you, how often do you answer truthfully?",
        "Has a stranger ever changed your life?",
        "What is the most unexplainable thing that's ever happened to you?",
        "Describe your perfect day!",
        "Have you changed your mind about anything recently?",
        "What's been the best compliment a stranger has ever given you?",
        "What is a compliment you wish you received more frequently?",
        "What do you crave more of?",
        "What has been your earliest recollection of happiness?",
        "What are you more afraid of, failure or success? And why?",
        "How would you describe the feeling of being in love in one word?",
        "When was the last time you surprised yourself?",
        "What's been your happiest memory this past year?",
        "Do you think the image you have of yourself matches the image people see you as?",
        "If you have, when was the moment you realized you weren't invincible?",
        "What lesson took you the longest to unlearn?",
        "What part of your life works? What part of your life hurts?",
        "What is your 1st love's name and the reason you fell in love with him/her?",
        "What's your mother's name? And the most beautiful thing about her?",
        "If you could get to know someone in your life on a deeper level, who would it be and why?",
        "Are you missing anyone right now? Do you think they are missing you too?",
        "What is a dream you've let go of?",
        "What is the last thing you lied to your mother about?",
        "Have you ever told someone I love you but didn't mean it? if so, why?",
        "How can you become a better person?",
    ], 
    
    level3: [
        "What can I help you with?",
        "Why do you think we met?",
        "What about me surprised you?",
        "In a word, how would you describe our conversation?",
        "What do you think my strength is?",
        "What can I teach you?",
        "Based on what you've learned about me, do you have any Netflix recommendations?",
        "Who do I remind you of?",
        "What can you be kinder towards yourself for today?",
        "What's one small thing you can do to be a better person in 2019?",
        "What can we create together?",
        "How would you describe me to a stranger?",
        "What about me most surprised you?",
        "What would be the perfect gift for me?",
        "What do you admire most about me?",
        "Based on what you learned about me, what book would you recommend I read?",
        "What about me is hardest for you to understand?",
        "What am I most qualified to give advice about?",
        "What is one thing you think I can do that would dramatically improve my life?",
        "If we were in a band, what would our name be?",
        "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
        "What do I need to hear right now?",
        "Based on what you know about me, do you have any netflix recommendations?",
        "What do you think my superpower is?",
        "What is a lesson you will take away from our conversation?",
        "When in this game did you feel most connected to me?",
        "How does one earn your vulnerability? Have I earned it? How can I earn more?",
        "What do you think our most important similarity is?",
        "In one word, how would you describe our conversation?",
        "What answer of mine made you light up?",
        "When this game is over, what will you remember about me?",
        "What question were you most afraid to answer?",
        "What parts of yourself do you see in me?",
        "How do our personalities complement each other?",
        "What do you think my weakness is?",
        "What would make you feel closer to me?",
        "What do you think I fear the most?",
        "What has this conversation taught you about yourself?",
        "What do you think I should know about myself that perhaps I'm unaware of?",
        "What do you think my defining characterisitic is?",
        "Do you believe everyone has a calling? If so, do you think I've found mine?",
        "What do you recommend I let go of, if anything?",
        "In one word, describe how you feel right now",
    ]
};

const regularIndonesia = {
    level1: [
        "Gimana kesan pertama kamu ketika melihat aku?",
        "Menurut kamu apa bagian paling susah dari pekerjaanku?",
        "Kalo menurut kamu, aku lebih suka kucing atau anjing?",
        "Apa sih yang bisa kamu simpulin tentang aku dari sepatu yang aku pake sekarang",
        "Menurut kamu aku lebih ke tipe kreatif atau analitis? Jelasin dong.",
        "Menurut kamu aku udah berapa kali ditilang?",
        "Menurut kamu apa sih yang paling mungkin membuat aku boros?",
        "Lanjutin kalimat ini: hanya dengan ngeliat kamu, aku berpikir ____.",
        "Aku mengingatkan kamu pada orang lain gak?",
        "Menurutmu, aku pernah ga sih cek hp mantan buat cari bukti?",
        "Hal pertama apa yang kamu sadari tentang aku?",
        "Aku kayaknya tipe orang yang suka kopi atau teh nih? Manis atau tidak?",
        "Kalo kamu harus beliin aku kado, cuma tau dari penampilanku aja, kira-kira mau beliin apa?",
        "Menurutmu aku keliatan baik gak? Jelasin dong.",
        "Menurutmu, aku mudah jatuh cinta ga sih? Kenapa?",
        "Menurut kamu cita-cita masa kecilku apa?",
        "Kira-kira menurutmu, biasanya aku datang lebih awal, tepat waktu, atau telat nih ke acara? Jelasin dong.",
        "Pelajaran apa yang menurut kamu aku paling jago waktu sekolah?",
        "Pujian apa yang paling sering aku denger menurutmu?",
        "Menurutmu aku ini morning person or demen begadang? Kenapa?",
        "Menurutmu aku ini populer waktu SMA ga sih? Jelasin dong.",
        "Menurutmu aku ini mengintimidasi orang lain gak sih? Jelasin",
        "Apa sih yang hal paling aneh atau asing dari aku?",
        "Apa sih yang bikin kamu penasaran tentang aku?",
        "Menurutmu, apa yang bisa dibilang dari gaya berpakianku?",
        "Menurutmu aku pernah patah hati gak?",
        "Kira-kira aku pernah jatuh cinta belum ya menurutmu?",
        "Apa asumsi terburuk yang pernah dibuat orang tentang kamu?"
    ],
    
    level2: [
        "Apa ciri khasmu yang paling menonjol?",
        "Apa rasa sakit terberat yang pernah kamu alami tapi yang bukan fisik?",
        "Jawab dengan jujur, gimana kabar kamu?",
        "Apakah mama kamu pernah bohong tentang sesuatu ke kamu?",
        "Siapa nama ayahmu dan sebutin satu hal tentang dia",
        "Apa sih yang udah kamu tahan dari orang-orang dulu yang sekarang ga bisa lagi aku toleransi?",
        "Ada sesuatu yang bikin aku senyum minggu ini, yaitu ___.",
        "Apa yang lagi sering kamu rasain akhir-akhir ini?",
        "Apa yang lagi kamu butuhin sekarang tapi ga mau omongin ke orang?",
        "Apa yang lagi kamu hadapi sekarang yang orang lain ga tau?",
        "Apa titik balik terbesar dalam hidup percintaan kamu?",
        "Apa sih yang hati kamu lagi bener-bener pengen sekarang?",
        "Apa sifat toksikmu yang bisa kamu akui?",
        "Siapa di hidupmu yang paling pantas dapet 'terima kasih' terbesar?",
        "Apa yang lagi kamu overthinking-in sekarang?",
        "Apa yang kamu pelajari tentang diri kamu sendiri dari hubungan terakhir?",
        "Apa yang kamu percaya dulu tapi sekarang udah gak lagi?",
        "Apa yang harus kamu maafkan dari diri kamu sendiri?",
        "Apa pelajaran terberat yang udah kamu pelajari dari hubungan percintaan?",
        "Kamu udah pernah sakitin aku, tapi terima kasih karena ___.",
        "Dengan siapa kamu bisa jadi paling terbuka di hidupmu?",
        "Sifat mana dari orangtuamu yang ingin kamu pertahankan/buang?",
        "Pesan untuk diriku di masa lalu: ____",
        "Pikirin seseorang yang kamu kagumi. Kenapa orang ini terlintas di pikiranmu?",
        "Apakah kamu sedang membohongi diri sendiri? Tentang apa?",
        "Apa bagian favoritmu dari diri sendiri yang bukan fisik?",
        "Hal paling berat ketika pacaran sama kamu",
        "Aku merasa dicintai kalo ___.",
        "Apa yang udah kamu pelajarin tentang diri kamu minggu ini?",
        "Self love adalah ___.",
        "Apa pelajaran yang bisa diambil dari pengalaman pahit terbaru kamu?",
        "Aku tau aku lagi jatuh cinta kalo ___.",
        "Sebutin satu bait dari lagu favorit kamu sekarang",
        "Gimana cara kamu move on dari cinta pertamamu?",
        "Apa pelajaran terbaik yang pernah diajarkan mantanmu?",
        "Ada gak orang yang udah mengubah hidupmu tapi dia ga tau?",
        "Apa yang paling kamu butuhin sekarang?",
        "Kapan terakhir kali kamu merasa beruntung jadi dirimu sendiri?",
        "Apa yang harus kamu terima hari ini?",
        "Kapan terakhir kali kamu merasa paling jadi dirimu sendiri?",
        "Siapa nama ibumu dan pelajaran paling berharga yang pernah dia ajarin ke kamu?",
        "Apa yang paling kamu syukuri sekarang ini?",
        "Apa yang masih coba kamu buktikan ke diri sendiri?",
        "Apa yang udah kamu kurang syukurin saat ini?",
        "Ada gak rasa yang kamu kangenin?",
        "Apa sih hal tentang hidupmu sekarang yang ga akan dipercaya oleh versi dirimu yang lebih muda?",
        "Kalo bisa sesuai keinginanmu: Kamu mau hidup sama siapa? Mau tinggal dimana? dan kerja jadi apa?",
        "Apa yang perlu kamu dengar sekarang?",
        "Apa judul yang pas buat fase hidupmu sekarang?",
        "Apa nasihat pacaran yang mau kamu kasih ke diri kamu yang lebih muda?",
        "Apa pelajaran yang seharusnya udah kamu pelajari sekarang?",
        "Kapan terakhir kali kamu pake rasa sakitmu untuk bantu orang lain?",
        "Apa yang ga pernah mau kamu ubah dari dirimu sendiri?",
        "Tahun ini udah mau selesai, ada gak hal yang belum kejawab di tahun ini?",
        "Apa tentang dirimu yang paling sulit untuk diakui?",
        "Apa pertanyaan terbesar yang lagi kamu cari jawabannya di hidupmu sekarang?",
        "Lanjutkan kalimat ini: orang lain menggambarkanku sebagai _____. Hanya aku yang tau bahwa aku adalah _____",
        "Kalo ditanya 'kamu gimana?' seberapa sering kamu jawab jujur?",
        "Pernah ga sih hidupmu berubah karena orang asing?",
        "Apa pengalaman paling ga bisa dijelaskan yang pernah kamu alami?",
        "Ceritain hari terbaik kamu!",
        "Apa hal yang baru-baru ini kamu rubah pikiran tentang itu?",
        "Apa pujian terbaik yang pernah kamu dengar dari orang asing?",
        "Apa pujian yang kamu harap sering kamu dengar?",
        "Apa yang kamu butuhin banget sekarang?",
        "Apa yang lebih kamu takutin, gagal atau sukses? Kenapa?",
        "Apa satu kata yang bisa gambarkan perasaan jatuh cinta menurutmu?",
        "Kapan terakhir kali kamu bikin diri kamu terkejut?",
        "Apa memori terbahagia di tahun ini?",
        "Apa bayanganmu tentang dirimu sendiri yang sama dengan bayangan orang lain tentangmu?",
        "Kalo iya, kapan kamu sadar bahwa kamu bukan manusia super?",
        "Apa kebiasaan lama yang perlu kamu hilangkan?",
        "Siapa nama cinta pertamamu dan kenapa kamu jatuh cinta sama dia/dia?",
        "Siapa nama ibumu? dan hal terindah dari dia apa?",
        "Kalo boleh kenal lebih dalam dengan seseorang di hidupmu, siapa dia dan kenapa?",
        "Ada orang yang lagi kamu kangen sekarang? Kira-kira dia juga kangen kamu gak?",
        "Apa impian yang udah kamu lepas?",
        "Pernah bohong ke ibu sendiri gak? Tentang apa?",
        "Pernah ga sih bilang 'I love you' ke seseorang tapi ga beneran? kalo iya, kenapa?",
        "Gimana sih caranya kamu jadi lebih baik lagi?"
    ], 
    
    level3: [
        "Apa yang bisa aku bantu buat kamu?",
        "Kenapa ya kita bisa ketemu menurut kamu?",
        "Apa yang bikin kamu kaget tentang aku?",
        "Gimana sih ngobrol sama aku menurut kamu? Jelasin dengan satu kata aja",
        "Menurut kamu, apa yang jadi kelebihan aku nih?",
        "Apa yang aku bisa ajarin ke kamu?",
        "Berdasarkan apa yang kamu tau tentang aku, ada rekomendasi Netflix ga yang kamu bisa kasih?",
        "Ada gak orang yang menurut kamu mirip sama aku?",
        "Apa yang bisa kamu lakukan hari ini untuk lebih baik ke diri sendiri?",
        "Satu hal kecil apa yang bisa bikin kamu jadi orang yang lebih baik di tahun 2019?",
        "Kedepannya, apa yang bisa kita lakuin bareng?",
        "Kalo ngomongin aku ke orang yang baru kamu kenal, kamu bakal bilang apa?",
        "Apa yang paling bikin kamu kaget tentang aku?",
        "Kado apa ya yang paling cocok buat aku menurut kamu?",
        "Apa yang paling kamu kagumin dari aku?",
        "Berdasarkan apa yang udah kamu tau tentang aku, kamu mau rekomendasiin buku apa?",
        "Hal apa di aku yang paling bikin kamu bingung ya?",
        "Tentang hal apa kamu butuh nasihat atau saran dari aku?",
        "Satu hal apa yang menurut kamu bisa memperbaiki hidup aku secara dramatis?",
        "Dari apa yang udah kamu tau soal aku, menurut kamu Instagram aku reflect diri aku beneran ga sih? Kenapa?",
        "Apa yang perlu aku denger sekarang menurut kamu?",
        "Apa superpower aku menurut kamu?",
        "Pelajaran apa nih yang bisa kamu petik dari obrolan kita?",
        "Kapan dalam game ini kamu ngerasa paling konek sama aku?",
        "Gimana caranya dapat kepercayaan dari kamu? Apakah aku udah dapet? Gimana caranya aku bisa dapat lebih banyak?",
        "Persamaan apa yang paling penting antara aku sama kamu?",
        "Gimana sih obrolan kita menurut kamu dengan satu kata aja?",
        "Dari semua pertanyaan tadi ,jawaban apa dari aku yang bikin kamu seneng dengernya",
        "Hal apa yang paling bakal kamu inget tentang aku kalo game ini selesai?",
        "Pertanyaan apa yang paling bikin kamu jiper buat jawab?",
        "Bagian apa dari diri kamu yang ada di aku ya?",
        "Apakah menurut kamu kita akur?",
        "Menurut kamu, apa kekurangan aku?",
        "Apa yang bisa bikin kamu lebih deket sama aku?",
        "Menurut kamu, apa ketakutan yang aku punya?",
        "Apa sih yang kamu bisa pelajari tentang diri kamu dari obrolan kita ini?",
        "Hal apa yang menurut kamu harus aku tau tentang diri aku yang mungkin belum aku sadari?",
        "Apa ya yang menurut kamu paling mendefinisikan aku?",
        "Kamu percaya ga sih kalo semua orang punya panggilan hati? Kalo iya, menurut kamu udah nemu belum panggilan aku?",
        "Menurut kamu, apa ya yang harus aku lepasin, kalo ada?",
        "Dengan satu kata, deskripsiin perasaan kamu sekarang."
    ]
}

export { regularEnglish, regularIndonesia };